'use strict';
const W=1280,H=720;
const input={left:false,right:false,jump:false,shoot:false};
let scene;
function rect(x,y,w,h,c){const g=scene.add.rectangle(x,y,w,h,c);scene.physics.add.existing(g,true);return g}
class Boot extends Phaser.Scene{
 constructor(){super('Boot')}
 create(){scene=this;this.cameras.main.setBackgroundColor('#171313');const g=this.make.graphics({x:0,y:0,add:false});g.fillStyle(0xffffff,1);g.fillRect(0,0,2,2);g.generateTexture('blank',2,2);g.destroy();this.add.text(W/2,H/2,'INKBOUND',{fontFamily:'Georgia',fontSize:'64px',color:'#f4e7d0'}).setOrigin(.5);this.time.delayedCall(300,()=>this.scene.start('Game'))}
}
class Game extends Phaser.Scene{
 constructor(){super('Game');this.story=true;this.hp=5;this.bossHP=20;this.coins=0;this.dead=false;this.won=false}
 create(){scene=this;this.physics.world.setBounds(0,0,3900,H);this.cameras.main.setBounds(0,0,3900,H);this.makeArt();this.makeLevel();this.makePlayer();this.makeUI();this.showStory();this.bindInput()}
 makeArt(){const bg=this.add.graphics();bg.fillGradientStyle(0x191b27,0x191b27,0x58382e,0x58382e,1);bg.fillRect(0,0,3900,H);bg.fillStyle(0x0d0e12,1);for(let i=0;i<45;i++){const x=i*100,h=90+(i*37%190);bg.fillRect(x,H*.70-h,72,h)}}
 makeLevel(){this.platforms=this.physics.add.staticGroup();[[0,504,520,216],[620,403,250,35],[950,518,350,202],[1400,382,300,35],[1760,490,430,230],[2290,396,330,35],[2710,504,420,216],[3180,382,330,35],[3540,504,360,216]].forEach(a=>{const p=this.platforms.create(a[0]+a[2]/2,a[1]+a[3]/2,'blank');p.setDisplaySize(a[2],a[3]);p.refreshBody();p.setTint(0x29262a)});
 this.spikes=this.physics.add.staticGroup();[[465,474,55],[815,373,55],[1250,488,60],[1640,352,60],[2160,460,70],[2630,474,65],[3100,352,65],[3470,474,60]].forEach(a=>{const s=this.spikes.create(a[0]+a[2]/2,a[1]+15,'blank');s.setDisplaySize(a[2],30);s.refreshBody();s.setTint(0xcf5058)});
 this.gems=this.physics.add.group();for(let i=0;i<13;i++){const g=this.gems.create(260+i*275,300+(i%3)*55,'blank');g.setCircle(9);g.setTint(0xefc65b);g.body.allowGravity=false}
 this.enemies=this.physics.add.group();[[1080,464],[1870,452],[2790,466]].forEach((a,i)=>{const e=this.enemies.create(a[0],a[1],'blank');e.setSize(38,38);e.setTint(0x814644);e.setVelocityX(i%2? -80:80);e.min=a[0]-120;e.max=a[0]+120;e.hp=3;e.body.allowGravity=true});
 this.boss=this.enemies.create(3030,250,'blank');this.boss.setSize(120,120);this.boss.setTint(0x6b659d);this.boss.body.allowGravity=false;this.boss.hp=20;this.boss.active=false;this.boss.setVisible(false);
 this.physics.add.overlap(this.player||[],this.spikes,()=>this.damage(),null,this);this.physics.add.overlap(this.player||[],this.enemies,(_,e)=>{if(e===this.boss)return;this.damage()},null,this);
 }
 makePlayer(){this.player=this.physics.add.sprite(110,460,'blank').setDisplaySize(30,44).setTint(0xeee5d4);this.player.setCollideWorldBounds(true);this.player.body.setMaxVelocity(500,900);this.physics.add.collider(this.player,this.platforms);this.physics.add.overlap(this.player,this.spikes,()=>this.damage(),null,this);this.physics.add.overlap(this.player,this.enemies,(p,e)=>{if(e!==this.boss)this.damage()},null,this);this.physics.add.overlap(this.player,this.gems,(p,g)=>{g.destroy();this.coins++},null,this);this.physics.add.overlap(this.player,this.boss,(p,b)=>{if(b.active)this.damage()},null,this);this.cameras.main.startFollow(this.player,true,.09,.09)}
 makeUI(){this.hud=this.add.text(20,20,'',{fontFamily:'Arial',fontSize:'18px',fontStyle:'bold',color:'#ffffff'}).setScrollFactor(0);this.fps=this.add.text(W-130,20,'120 FPS READY',{fontFamily:'Arial',fontSize:'14px',color:'#ffffff'}).setScrollFactor(0);this.controls();}
 controls(){const mk=(x,y,label,key)=>{const b=this.add.circle(x,y,42,0x151515,.68).setScrollFactor(0).setStrokeStyle(2,0xffffff,.65).setInteractive();this.add.text(x,y,label,{fontFamily:'Arial',fontSize:'28px',color:'#fff',fontStyle:'bold'}).setOrigin(.5).setScrollFactor(0);b.on('pointerdown',()=>input[key]=true);b.on('pointerup',()=>input[key]=false);b.on('pointerout',()=>input[key]=false)};mk(62,H-55,'◀','left');mk(150,H-55,'▶','right');mk(W-150,H-55,'↑','jump');mk(W-62,H-55,'◆','shoot')}
 bindInput(){this.keys=this.input.keyboard.addKeys({left:'A',right:'D',jump:'W',jump2:'SPACE',shoot:'SHIFT'});this.input.keyboard.on('keydown-LEFT',()=>input.left=true);this.input.keyboard.on('keyup-LEFT',()=>input.left=false);this.input.keyboard.on('keydown-RIGHT',()=>input.right=true);this.input.keyboard.on('keyup-RIGHT',()=>input.right=false);this.input.keyboard.on('keydown-UP',()=>input.jump=true);this.input.keyboard.on('keyup-UP',()=>input.jump=false);this.input.keyboard.on('keydown-X',()=>input.shoot=true);this.input.keyboard.on('keyup-X',()=>input.shoot=false)}
 showStory(){this.story=true;this.overlay=this.add.rectangle(W/2,H/2,W,H,0x000000,.68).setScrollFactor(0);this.storyTitle=this.add.text(W/2,H/2-80,'THE LAST MATCH',{fontFamily:'Georgia',fontSize:'34px',color:'#f7ead5'}).setOrigin(.5).setScrollFactor(0);this.storyText=this.add.text(W/2,H/2,`The sun vanished three nights ago.\nRook carries the last living match.\nReach the old theatre before the flame dies.`,{fontFamily:'Georgia',fontSize:'20px',color:'#f7ead5',align:'center',lineSpacing:8}).setOrigin(.5).setScrollFactor(0);this.storyButton=this.add.text(W/2,H/2+105,'TAP TO CONTINUE',{fontFamily:'Georgia',fontSize:'18px',color:'#e5b94e'}).setOrigin(.5).setInteractive().setScrollFactor(0);this.storyButton.on('pointerdown',()=>this.closeStory())}
 closeStory(){this.story=false;[this.overlay,this.storyTitle,this.storyText,this.storyButton].forEach(o=>o.destroy())}
 damage(){if(this.player.inv>0||this.dead||this.won||this.story)return;this.hp--;this.player.inv=60;this.player.setAlpha(.45);this.time.delayedCall(600,()=>this.player&&this.player.setAlpha(1));this.player.setVelocityY(-330);if(this.hp<=0)this.end(false)}
 end(win){this.won=win;this.dead=!win;this.scene.pause();const ov=this.add.rectangle(W/2,H/2,W,H,0x000000,.78).setScrollFactor(0);this.add.text(W/2,H/2-60,win?'DAWN RETURNS':'GAME OVER',{fontFamily:'Georgia',fontSize:'54px',color:'#f7ead5'}).setOrigin(.5).setScrollFactor(0);const t=win?'The theatre doors open. Bellweather sees the sun.':'The match goes dark. Try again.';this.add.text(W/2,H/2+10,t,{fontFamily:'Georgia',fontSize:'19px',color:'#f7ead5'}).setOrigin(.5).setScrollFactor(0);const b=this.add.text(W/2,H/2+90,'RESTART',{fontFamily:'Georgia',fontSize:'20px',color:'#e5b94e'}).setOrigin(.5).setInteractive().setScrollFactor(0);b.on('pointerdown',()=>this.scene.restart())}
 update(){if(this.story||this.dead||this.won)return;const p=this.player;let vx=0;if(input.left||this.keys.left.isDown||this.keys.LEFT?.isDown)vx=-240;if(input.right||this.keys.right.isDown||this.keys.RIGHT?.isDown)vx=240;p.setVelocityX(vx);if((input.jump||this.keys.jump.isDown||this.keys.jump2.isDown)&&p.body.blocked.down){p.setVelocityY(-570);input.jump=false}if(input.shoot||this.keys.shoot.isDown){if(!this.lastShot||this.time.now-this.lastShot>240){this.shoot();this.lastShot=this.time.now}input.shoot=false}if(this.boss.x-p.x<700)this.boss.active=true,this.boss.setVisible(true);for(const e of this.enemies.getChildren()){if(e===this.boss)continue;if(e.x<e.min||e.x>e.max)e.setVelocityX(-e.body.velocity.x)}if(this.boss.active&&this.boss.hp>0){this.boss.x=3030;this.boss.y=250+Math.sin(this.time.now/280)*55}if(this.boss.hp<=0)this.boss.setVisible(false);if(p.x>3700&&this.boss.hp<=0)this.end(true);this.hud.setText(`♥ ${this.hp}   💰 ${this.coins}   BOSS ${this.boss.active?this.boss.hp+'/20':''}`)}
 shoot(){const dir=this.player.body.velocity.x>=0?1:-1;const b=this.physics.add.image(this.player.x+dir*24,this.player.y,'blank').setDisplaySize(16,8).setTint(0xf2c65b);b.body.allowGravity=false;b.setVelocityX(this.player.body.velocity.x>=0?650:-650);this.physics.add.overlap(b,this.enemies,(bullet,e)=>{if(e===this.boss&&e.hp>0){e.hp--;bullet.destroy()}else if(e!==this.boss){e.hp--;bullet.destroy();if(e.hp<=0)e.destroy()}})}
}
const config={type:Phaser.AUTO,parent:'game',width:W,height:H,backgroundColor:'#171313',render:{antialias:true,powerPreference:'high-performance'},fps:{target:120,forceSetTimeOut:false,deltaHistory:10},scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},physics:{default:'arcade',arcade:{gravity:{y:1100},debug:false}},scene:[Boot,Game],input:{activePointers:4}};
// One tiny generated texture keeps the project asset-free.
new Phaser.Game(config);
